// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5RfpUQedv1iXBHUr2LHsn4SO3i3JMJmk',
    appId: '1:7900965809:web:9bb289d43968fb78796b90',
    messagingSenderId: '7900965809',
    projectId: 'loginhospital-2cc49',
    authDomain: 'loginhospital-2cc49.firebaseapp.com',
    storageBucket: 'loginhospital-2cc49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNX_xFvLuPY497tMipDJvvUBsa6DII5A',
    appId: '1:7900965809:android:adf4bcc20770e139796b90',
    messagingSenderId: '7900965809',
    projectId: 'loginhospital-2cc49',
    storageBucket: 'loginhospital-2cc49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi5qtX1xCtKsIoXfXeowsysk6FDIzz9KU',
    appId: '1:7900965809:ios:f73c65d70873fa13796b90',
    messagingSenderId: '7900965809',
    projectId: 'loginhospital-2cc49',
    storageBucket: 'loginhospital-2cc49.appspot.com',
    iosClientId: '7900965809-5dq4m7ba3n1di1i821t9kg6o1iao24k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi5qtX1xCtKsIoXfXeowsysk6FDIzz9KU',
    appId: '1:7900965809:ios:f73c65d70873fa13796b90',
    messagingSenderId: '7900965809',
    projectId: 'loginhospital-2cc49',
    storageBucket: 'loginhospital-2cc49.appspot.com',
    iosClientId: '7900965809-5dq4m7ba3n1di1i821t9kg6o1iao24k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentUi',
  );
}
